services:
  # Production services
  mysqldb:
    image: mysql:8.4
    container_name: ai-judge-mysql-db
    profiles:
      - dev
      - prod
      - test
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1' || exit 1"
        ]
      interval: 5s
      retries: 20
      start_period: 5s
    networks:
      - ai-judge-network
  api:
    container_name: ai-judge-api
    build: ./api
    profiles:
      - dev
      - prod
    env_file: .env
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    depends_on:
      mysqldb:
        condition: service_healthy    
    networks:
      - ai-judge-network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${API_DOCKER_PORT}/openapi.json || curl -f http://localhost:${API_DOCKER_PORT}/health || exit 1"]
      interval: 15s
      retries: 5
      start_period: 7s
    volumes:
      - ${STORAGE_DIR_VIDEOS}:${STORAGE_DIR_VIDEOS}
      - ${STORAGE_DIR_GENERATED_DATA}:${STORAGE_DIR_GENERATED_DATA}
      - ${MYSQL_BACKUP}:${MYSQL_BACKUP}
      - ./computervision/recipes.json:/machine_learning_recipes.json:ro
  web:
    container_name: ai-judge-web
    build: ./web
    profiles:
      - dev
      - prod
    env_file: .env
    ports:
      - $WEB_LOCAL_PORT:$WEB_DOCKER_PORT
    depends_on:
      api:
        condition: service_healthy
    networks:
      - ai-judge-network
    restart: on-failure
  computervision:
    container_name: ai-judge-computer-vision
    build: ./computervision
    profiles:
      - prod
      - dev
    gpus: all
    env_file: .env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - ai-judge-network
    volumes:
      - ${STORAGE_DIR_VIDEOS}:${STORAGE_DIR_VIDEOS}
      - ${STORAGE_DIR_GENERATED_DATA}:${STORAGE_DIR_GENERATED_DATA}
      - torch_cache:/root/.cache/torch
    # ipc: host # Good for now - use shm_size
    shm_size: 6gb # About 30-50% max of CPU

  # Testing services
  api-test:
    container_name: ai-judge-api-test
    build: ./api
    profiles:
      - test
      - prod
    env_file: .env.test
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - ai-judge-network
    command: ["python", "-m", "unittest", "discover"]
    volumes:
      - api_test:${STORAGE_DIR_VIDEOS}
      - api_test:${STORAGE_DIR_GENERATED_DATA}
      - api_test:${MYSQL_BACKUP}
      - ./computervision/recipes.json:/machine_learning_recipes.json:ro

networks:
  ai-judge-network:
    driver: bridge

volumes:
  torch_cache:
  api_test:

