# Additional override params for docker-compose for development environment
services:
  api:
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: no
    volumes:
      - ./api:/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=${API_DOCKER_PORT}", "--reload"]
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
    - ./web:/app
    - /app/node_modules    # Preserve container node_modules
  computervision:
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./computervision:/app
      - ${STORAGE_DIR_VIDEOS}:${STORAGE_DIR_VIDEOS}
      - ${STORAGE_DIR_GENERATED_DATA}:${STORAGE_DIR_GENERATED_DATA}
    command: ["python", "JobExecuter.py"]

  api-test:
    environment:
      - PYTHONUNBUFFERED=1

