"""optional taggroup

Revision ID: 0143388f4f97
Revises: 5e57a9296eb8
Create Date: 2025-07-11 11:13:37.819870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0143388f4f97'
down_revision = '5e57a9296eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.alter_column('tagGroupId',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.alter_column('tagGroupId',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
