"""add frameLength

Revision ID: 0206388820d7
Revises: 59a6795c796f
Create Date: 2024-12-27 19:49:08.752679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0206388820d7'
down_revision = '59a6795c796f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frameLength', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_column('frameLength')

    # ### end Alembic commands ###
