"""adding default levels dd & cw

Revision ID: 075ec79e0e90
Revises: b9bdf7a05a5a
Create Date: 2025-02-11 15:33:29.504348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '075ec79e0e90'
down_revision = 'b9bdf7a05a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.alter_column('level_dd',
               existing_type=mysql.VARCHAR(length=7),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('level_cw',
               existing_type=mysql.VARCHAR(length=7),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.alter_column('level_cw',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.alter_column('level_dd',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
