"""add TagGroup parent

Revision ID: 111ed43f1d41
Revises: d35454169b5f
Create Date: 2025-07-24 16:09:03.291004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111ed43f1d41'
down_revision = 'd35454169b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TagGroups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'TagGroups', ['parentId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TagGroups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parentId')

    # ### end Alembic commands ###
