"""add conflictlog, deletedvideo, exportjob

Revision ID: 1917fc57e9ec
Revises: 473abb577f52
Create Date: 2026-03-14 21:57:27.147385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1917fc57e9ec'
down_revision = '473abb577f52'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConflictLogs',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BINARY(length=16), nullable=False),
    sa.Column('winning_account_id', sa.BINARY(length=16), nullable=False),
    sa.Column('winning_region', sa.String(length=50), nullable=False),
    sa.Column('winning_timestamp', sa.DateTime(), nullable=False),
    sa.Column('winning_data', mysql.JSON(), nullable=False),
    sa.Column('losing_account_id', sa.BINARY(length=16), nullable=True),
    sa.Column('losing_region', sa.String(length=50), nullable=False),
    sa.Column('losing_timestamp', sa.DateTime(), nullable=False),
    sa.Column('losing_data', mysql.JSON(), nullable=False),
    sa.Column('conflict_description', sa.String(length=255), nullable=False),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.BINARY(length=16), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['losing_account_id'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['winning_account_id'], ['Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ConflictLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ConflictLogs_entity_id'), ['entity_id'], unique=False)

    op.create_table('DeletedVideos',
    sa.Column('video_id', sa.BINARY(length=16), nullable=False),
    sa.Column('video_name', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.BINARY(length=16), nullable=False),
    sa.Column('deleted_by', sa.BINARY(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('recovery_deadline', sa.DateTime(), nullable=False),
    sa.Column('hard_delete_at', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('original_video_data', mysql.JSON(), nullable=False),
    sa.Column('storage_path', sa.String(length=511), nullable=False),
    sa.Column('is_hard_deleted', sa.Boolean(), nullable=False),
    sa.Column('hard_deleted_by', sa.BINARY(length=16), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['Accounts.id'], ),
    sa.ForeignKeyConstraint(['hard_deleted_by'], ['Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('DeletedVideos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DeletedVideos_video_id'), ['video_id'], unique=True)

    op.create_table('ExportJobs',
    sa.Column('account_id', sa.BINARY(length=16), nullable=False),
    sa.Column('include_metadata', sa.Boolean(), nullable=False),
    sa.Column('include_training_results', sa.Boolean(), nullable=False),
    sa.Column('include_frames', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('estimated_size_gb', sa.Float(), nullable=True),
    sa.Column('actual_size_gb', sa.Float(), nullable=True),
    sa.Column('download_url', sa.String(length=511), nullable=True),
    sa.Column('file_path', sa.String(length=511), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=511), nullable=True),
    sa.Column('requested_by', sa.BINARY(length=16), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ExportJobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ExportJobs_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('Jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_category', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Jobs', schema=None) as batch_op:
        batch_op.drop_column('job_category')

    with op.batch_alter_table('ExportJobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ExportJobs_account_id'))

    op.drop_table('ExportJobs')
    with op.batch_alter_table('DeletedVideos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DeletedVideos_video_id'))

    op.drop_table('DeletedVideos')
    with op.batch_alter_table('ConflictLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ConflictLogs_entity_id'))

    op.drop_table('ConflictLogs')
    # ### end Alembic commands ###

