"""remove unused tables

Revision ID: 21f523e55efd
Revises: bc617d419a00
Create Date: 2025-08-22 22:06:09.952169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21f523e55efd'
down_revision = 'bc617d419a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Skillinfo_DoubleDutch')
    op.drop_table('Predictions_Localization')
    op.drop_table('ML_Models')
    op.drop_table('Skillinfo_DoubleDutch_Skill')
    op.drop_table('Skillinfo_DoubleDutch_Turner')
    op.drop_table('Skillinfo_DoubleDutch_Type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Skillinfo_DoubleDutch_Type',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Skillinfo_DoubleDutch_Turner',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=127), nullable=False),
    sa.Column('level_dd', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('level_cw', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('cw_requires_both', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('dd_requires_both', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Skillinfo_DoubleDutch_Skill',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=127), nullable=False),
    sa.Column('level_dd', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('level_cw', mysql.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ML_Models',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Predictions_Localization',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('videoId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frameNr', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locationChecked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('segmentSplitValue', mysql.FLOAT(), nullable=True),
    sa.Column('segmentsChecked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('predictionDate', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], name=op.f('Predictions_Localization_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Skillinfo_DoubleDutch',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('videoId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frameStart', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frameEnd', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('rotations', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('turner1', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('turner2', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('skill', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('hands', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('feet', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('turntable', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('bodyRotations', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('backwards', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sloppy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('hard2see', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fault', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('labeldate', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['skill'], ['Skillinfo_DoubleDutch_Skill.id'], name=op.f('Skillinfo_DoubleDutch_ibfk_1')),
    sa.ForeignKeyConstraint(['turner1'], ['Skillinfo_DoubleDutch_Turner.id'], name=op.f('Skillinfo_DoubleDutch_ibfk_2')),
    sa.ForeignKeyConstraint(['turner2'], ['Skillinfo_DoubleDutch_Turner.id'], name=op.f('Skillinfo_DoubleDutch_ibfk_3')),
    sa.ForeignKeyConstraint(['type'], ['Skillinfo_DoubleDutch_Type.id'], name=op.f('Skillinfo_DoubleDutch_ibfk_4')),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], name=op.f('Skillinfo_DoubleDutch_ibfk_5')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
