"""adding default levels dd & cw

Revision ID: 38db06b11c42
Revises: fbded2d8de76
Create Date: 2025-02-11 15:39:10.366125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38db06b11c42'
down_revision = 'fbded2d8de76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_dd', mysql.TINYINT(unsigned=True), nullable=False))
        batch_op.add_column(sa.Column('level_cw', mysql.TINYINT(unsigned=True), nullable=False))
        batch_op.add_column(sa.Column('cw_requires_both', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.drop_column('cw_requires_both')
        batch_op.drop_column('level_cw')
        batch_op.drop_column('level_dd')

    # ### end Alembic commands ###
