"""add folder.is_train and video.is_train

Revision ID: 473abb577f52
Revises: 6faf4b9aaf9f
Create Date: 2026-02-28 13:45:07.596697

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '473abb577f52'
down_revision = '6faf4b9aaf9f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_train', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_train', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_column('is_train')

    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.drop_column('is_train')

    # ### end Alembic commands ###

