"""add skill hard to see

Revision ID: 498bedd51e1c
Revises: d6c43649b574
Create Date: 2025-02-09 10:47:00.419540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498bedd51e1c'
down_revision = 'd6c43649b574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hard2see', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch', schema=None) as batch_op:
        batch_op.drop_column('hard2see')

    # ### end Alembic commands ###
