"""adding default levels dd & cw

Revision ID: 4d369a28c2d0
Revises: e9247e7070ae
Create Date: 2025-02-11 15:55:39.738915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d369a28c2d0'
down_revision = 'e9247e7070ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Skill', schema=None) as batch_op:
        batch_op.alter_column('level_dd',
               existing_type=mysql.VARCHAR(length=127),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('level_cw',
               existing_type=mysql.VARCHAR(length=127),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Skill', schema=None) as batch_op:
        batch_op.alter_column('level_cw',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=127),
               existing_nullable=False)
        batch_op.alter_column('level_dd',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=127),
               existing_nullable=False)

    # ### end Alembic commands ###
