"""adding default levels dd & cw

Revision ID: 4ef14bf3ac25
Revises: 38db06b11c42
Create Date: 2025-02-11 15:47:01.613952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef14bf3ac25'
down_revision = '38db06b11c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dd_requires_both', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.drop_column('dd_requires_both')

    # ### end Alembic commands ###
