"""Add table Skill -> meet new skill label options

Revision ID: 537b5dd08060
Revises: 7f3bcfcaa1af
Create Date: 2025-08-06 15:48:28.570447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '537b5dd08060'
down_revision = '7f3bcfcaa1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('frameStart', sa.Integer(), nullable=False),
    sa.Column('frameEnd', sa.Integer(), nullable=False),
    sa.Column('skillinfo', mysql.JSON(), nullable=False),
    sa.Column('labeldate', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Skills')
    # ### end Alembic commands ###
