"""add sources table

Revision ID: 553f875bdce7
Revises: 6675718a9dd1
Create Date: 2025-01-15 14:47:14.175451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '553f875bdce7'
down_revision = '6675718a9dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sourceInfo', sa.String(length=255), nullable=True))
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('sourceInfo')

    op.drop_table('Sources')
    # ### end Alembic commands ###
