"""qualitative

Revision ID: 59a6795c796f
Revises: f3d97f292a0b
Create Date: 2024-12-27 13:45:14.933209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59a6795c796f'
down_revision = 'f3d97f292a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualitative', sa.Boolean(), nullable=False))
        batch_op.drop_column('quality')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('qualitative')

    # ### end Alembic commands ###
