"""Add users

Revision ID: 5c977a30fd2e
Revises: eee2a9301d3f
Create Date: 2026-02-07 21:16:45.800822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c977a30fd2e'
down_revision = 'eee2a9301d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=127), nullable=False),
    sa.Column('lastName', sa.String(length=127), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('mfaEnabled', sa.Boolean(), nullable=False),
    sa.Column('mfaCode', sa.String(length=6), nullable=True),
    sa.Column('mfaCodeExpires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
