"""add tags and tagroups

Revision ID: 5e57a9296eb8
Revises: 0228456eb123
Create Date: 2025-07-11 10:12:24.699437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e57a9296eb8'
down_revision = '0228456eb123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TagGroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('tagGroupId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tagGroupId'], ['TagGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_tag',
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('tagId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tagId'], ['Tags.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('videoId', 'tagId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_tag')
    op.drop_table('Tags')
    op.drop_table('TagGroups')
    # ### end Alembic commands ###
