"""remove training field on video and make is_train nullable

Revision ID: 5f565036bae5
Revises: 1917fc57e9ec
Create Date: 2026-03-15 08:48:21.450497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f565036bae5'
down_revision = '1917fc57e9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.alter_column('is_train',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_column('training')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.alter_column('is_train',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
