"""video judge diff score

Revision ID: 615a4e6783e6
Revises: f1b872d0d749
Create Date: 2025-05-16 20:22:55.610424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615a4e6783e6'
down_revision = 'f1b872d0d749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judgeDiffScore', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_column('judgeDiffScore')

    # ### end Alembic commands ###
