"""add cascading

Revision ID: 62083299fe22
Revises: 21f523e55efd
Create Date: 2025-12-26 11:32:40.104036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62083299fe22'
down_revision = '21f523e55efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Folders_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Folders', ['parentId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FrameLabels_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('FrameLabels_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Videos', ['videoId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'FrameLabelTypes', ['labeltype'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('LayerComposition', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('LayerComposition_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'LayerProperties', ['propertyId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('LayerPropertyValues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('LayerPropertyValues_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'LayerProperties', ['propertyId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Skills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Skills_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Videos', ['videoId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('TagGroups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('TagGroups_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'TagGroups', ['parentId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Videos_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('Videos_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'CompetitionInfo', ['competition'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Folders', ['folderId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('video_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('video_tag_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('video_tag_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tags', ['tagId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Videos', ['videoId'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('video_tag_ibfk_2'), 'Videos', ['videoId'], ['id'])
        batch_op.create_foreign_key(batch_op.f('video_tag_ibfk_1'), 'Tags', ['tagId'], ['id'])

    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Videos_ibfk_2'), 'Folders', ['folderId'], ['id'])
        batch_op.create_foreign_key(batch_op.f('Videos_ibfk_1'), 'CompetitionInfo', ['competition'], ['id'])

    with op.batch_alter_table('TagGroups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('TagGroups_ibfk_1'), 'TagGroups', ['parentId'], ['id'])

    with op.batch_alter_table('Skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Skills_ibfk_1'), 'Videos', ['videoId'], ['id'])

    with op.batch_alter_table('LayerPropertyValues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('LayerPropertyValues_ibfk_1'), 'LayerProperties', ['propertyId'], ['id'])

    with op.batch_alter_table('LayerComposition', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('LayerComposition_ibfk_1'), 'LayerProperties', ['propertyId'], ['id'])

    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FrameLabels_ibfk_1'), 'FrameLabelTypes', ['labeltype'], ['id'])
        batch_op.create_foreign_key(batch_op.f('FrameLabels_ibfk_2'), 'Videos', ['videoId'], ['id'])

    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Folders_ibfk_1'), 'Folders', ['parentId'], ['id'])

    # ### end Alembic commands ###
