"""add l layer properties, layer property value

Revision ID: 65c4ed988090
Revises: 6704c28762a7
Create Date: 2025-07-25 11:46:02.658624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c4ed988090'
down_revision = '6704c28762a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LayerProperties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('step', sa.Float(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LayerPropertyValues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('propertyId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propertyId'], ['LayerProperties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LayerPropertyValues')
    op.drop_table('LayerProperties')
    # ### end Alembic commands ###
