"""videosource

Revision ID: 6675718a9dd1
Revises: a61f18a4fcdf
Create Date: 2025-01-14 19:19:52.848114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6675718a9dd1'
down_revision = 'a61f18a4fcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
