"""add tag keywords

Revision ID: 6704c28762a7
Revises: 111ed43f1d41
Create Date: 2025-07-24 16:37:51.792101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6704c28762a7'
down_revision = '111ed43f1d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=511), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
