"""empty message

Revision ID: 67a050a76d35
Revises: 10923fcf1075
Create Date: 2025-02-23 17:14:04.924677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a050a76d35'
down_revision = '10923fcf1075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labeldate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch', schema=None) as batch_op:
        batch_op.drop_column('labeldate')

    # ### end Alembic commands ###
