"""frame label type (individual vs all)

Revision ID: 6c2b133ef122
Revises: d6c43a490c73
Create Date: 2025-01-24 21:08:21.929139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2b133ef122'
down_revision = 'd6c43a490c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FrameLabelTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labeltype', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.drop_column('labeltype')

    op.drop_table('FrameLabelTypes')
    # ### end Alembic commands ###
