"""Initial migration

Revision ID: 6faf4b9aaf9f
Revises: 
Create Date: 2026-02-22 08:50:04.223826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6faf4b9aaf9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=127), nullable=False),
    sa.Column('lastName', sa.String(length=127), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.Column('mfaEnabled', sa.Boolean(), nullable=False),
    sa.Column('mfaCode', sa.String(length=6), nullable=True),
    sa.Column('mfaCodeExpires', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('CompetitionInfo',
    sa.Column('info', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Folders',
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('parentId', sa.BINARY(length=16), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['Folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parentId', name='_name_parent_unique_constraint')
    )
    op.create_table('FrameLabelTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Jobs',
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('step', sa.String(length=127), nullable=False),
    sa.Column('job_arguments', mysql.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_details', sa.String(length=127), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Layers',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('step', sa.Float(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sources',
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TagGroups',
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('parentId', sa.BINARY(length=16), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['TagGroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('TrainResults',
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('recipeCode', sa.String(length=255), nullable=False),
    sa.Column('recipe', mysql.JSON(), nullable=False),
    sa.Column('bestEpoch', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('revalidationResults', mysql.JSON(), nullable=False),
    sa.Column('lastRevalidationTime', sa.DateTime(), nullable=True),
    sa.Column('isBestOfAll', sa.Boolean(), nullable=False),
    sa.Column('isBestOfRecipe', sa.Boolean(), nullable=False),
    sa.Column('isBestOfArchitecture', sa.Boolean(), nullable=False),
    sa.Column('isTestrun', sa.Boolean(), nullable=False),
    sa.Column('trainEnd', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LayerComposition',
    sa.Column('compositionName', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('layerId', sa.BINARY(length=16), nullable=False),
    sa.Column('defaultValue', sa.String(length=15), nullable=True),
    sa.Column('focussed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layerId'], ['Layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LayerValues',
    sa.Column('layerId', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layerId'], ['Layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tags',
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('keywords', sa.String(length=511), nullable=True),
    sa.Column('tagGroupId', sa.BINARY(length=16), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tagGroupId'], ['TagGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TrainResultsEpoch',
    sa.Column('trainResultId', sa.BINARY(length=16), nullable=False),
    sa.Column('epoch', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('validationResults', mysql.JSON(), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trainResultId'], ['TrainResults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Videos',
    sa.Column('folderId', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frameLength', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('training', sa.Boolean(), nullable=False),
    sa.Column('qualitative', sa.Boolean(), nullable=False),
    sa.Column('obstruction', sa.Boolean(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('sourceInfo', sa.String(length=255), nullable=True),
    sa.Column('completed_skill_labels', sa.Boolean(), nullable=False),
    sa.Column('competition', sa.BINARY(length=16), nullable=True),
    sa.Column('judgeDiffScore', sa.Float(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition'], ['CompetitionInfo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folderId'], ['Folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'folderId', name='_name_folder_unique_constraint')
    )
    op.create_table('FrameLabels',
    sa.Column('videoId', sa.BINARY(length=16), nullable=False),
    sa.Column('frameNr', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('jumperVisible', sa.Boolean(), nullable=False),
    sa.Column('labeltype', sa.Integer(), nullable=False),
    sa.Column('labeldate', sa.Date(), nullable=True),
    sa.Column('labeltime', sa.Time(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['labeltype'], ['FrameLabelTypes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skills',
    sa.Column('videoId', sa.BINARY(length=16), nullable=False),
    sa.Column('frameStart', sa.Integer(), nullable=False),
    sa.Column('frameEnd', sa.Integer(), nullable=False),
    sa.Column('skillinfo', mysql.JSON(), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_tag',
    sa.Column('videoId', sa.BINARY(length=16), nullable=False),
    sa.Column('tagId', sa.BINARY(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tagId'], ['Tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('videoId', 'tagId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_tag')
    op.drop_table('Skills')
    op.drop_table('FrameLabels')
    op.drop_table('Videos')
    op.drop_table('TrainResultsEpoch')
    op.drop_table('Tags')
    op.drop_table('LayerValues')
    op.drop_table('LayerComposition')
    op.drop_table('TrainResults')
    op.drop_table('TagGroups')
    op.drop_table('Sources')
    op.drop_table('Layers')
    op.drop_table('Jobs')
    op.drop_table('FrameLabelTypes')
    op.drop_table('Folders')
    op.drop_table('CompetitionInfo')
    op.drop_table('Accounts')
    # ### end Alembic commands ###
