"""skill add faults

Revision ID: 79ebd221b252
Revises: 498bedd51e1c
Create Date: 2025-02-09 12:43:21.481671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ebd221b252'
down_revision = '498bedd51e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fault', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch', schema=None) as batch_op:
        batch_op.drop_column('fault')

    # ### end Alembic commands ###
