"""multi labels, remove unique contraint videoId-frameNr

Revision ID: 80e434a0dfc0
Revises: 947c56fb0186
Create Date: 2025-01-24 23:07:53.220284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e434a0dfc0'
down_revision = '947c56fb0186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
