"""taggroup unique name

Revision ID: 87684ae3df9a
Revises: 0143388f4f97
Create Date: 2025-07-11 12:07:33.345410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87684ae3df9a'
down_revision = '0143388f4f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TagGroups', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TagGroups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
