"""tricky migrate

Revision ID: 8bb04f93bdde
Revises: 3a5964126981
Create Date: 2026-01-04 20:14:22.093595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '8bb04f93bdde'
down_revision = '3a5964126981'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    insp = inspect(conn)

    columns = {c["name"] for c in insp.get_columns("LayerComposition")}
    fks = insp.get_foreign_keys("LayerComposition")

    for fk in insp.get_foreign_keys("LayerComposition"):
        if fk["name"] == "LayerComposition_layerId_fk":
            op.drop_constraint(
                "LayerComposition_layerId_fk",
                "LayerComposition",
                type_="foreignkey",
            )

    columns = {c["name"] for c in insp.get_columns("LayerComposition")}

    with op.batch_alter_table("LayerComposition") as batch_op:
        # Drop incorrectly populated layerId if both exist
        if "layerId" in columns and "propertyId" in columns:
            batch_op.drop_column("layerId")
            columns.remove('layerId')

        # Rename propertyId -> layerId if it still exists
        if "layerId" not in columns and "propertyId" in columns:
            batch_op.alter_column(
                "propertyId",
                new_column_name="layerId",
                existing_type=sa.Integer(),
                nullable=False,
            )
            columns.remove('propertyId')

            # batch_op.add_column(sa.Column("layerId", sa.Integer(), nullable=False))

        # drop FK to LayerProperties if it exists
        for fk in fks:
            if fk["referred_table"] == "LayerProperties":
                batch_op.drop_constraint(fk["name"], type_="foreignkey")

        # create FK to Layers only if missing
        if not any(
            fk["referred_table"] == "Layers" and "layerId" in fk["constrained_columns"]
            for fk in fks
        ):
            batch_op.create_foreign_key(
                "LayerComposition_layerId_fk",
                "Layers",
                ["layerId"],
                ["id"],
                ondelete="CASCADE",
            )

        if "propertyId" in columns:
            batch_op.drop_column("propertyId")

        if "name" in columns:
            batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LayerValues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('propertyId'), ['layerId'], unique=False)

    with op.batch_alter_table('LayerComposition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('propertyId', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('LayerComposition_ibfk_1'), 'LayerProperties', ['propertyId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('layerId')

    op.create_table('LayerPropertyValues',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('propertyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('creationDate', mysql.DATETIME(), nullable=True),
    sa.Column('lastUpdated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('LayerProperties',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('min', mysql.FLOAT(), nullable=True),
    sa.Column('max', mysql.FLOAT(), nullable=True),
    sa.Column('step', mysql.FLOAT(), nullable=True),
    sa.Column('creationDate', mysql.DATETIME(), nullable=True),
    sa.Column('lastUpdated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
