"""jobs

Revision ID: 8d01cde2bed1
Revises: 34f0595b6d7f
Create Date: 2025-05-08 12:34:18.747631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d01cde2bed1'
down_revision = '34f0595b6d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('step', sa.String(length=127), nullable=False),
    sa.Column('job_arguments', mysql.JSON(), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_details', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Jobs')
    # ### end Alembic commands ###
