"""add layercomposition

Revision ID: 8e61a70bdfdc
Revises: eff7ee2a451a
Create Date: 2025-07-31 10:17:41.512165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e61a70bdfdc'
down_revision = 'eff7ee2a451a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LayerComposition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compositionName', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('propertyId', sa.Integer(), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propertyId'], ['LayerProperties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LayerComposition')
    # ### end Alembic commands ###
