"""framelength unsigned smallint

Revision ID: 94224f7149ae
Revises: 0206388820d7
Create Date: 2024-12-27 19:55:20.397949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94224f7149ae'
down_revision = '0206388820d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.alter_column('frameLength',
               existing_type=mysql.INTEGER(),
               type_=mysql.SMALLINT(unsigned=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.alter_column('frameLength',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
