"""frame label type (individual vs all) - fk

Revision ID: 947c56fb0186
Revises: 6c2b133ef122
Create Date: 2025-01-24 21:12:27.222547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947c56fb0186'
down_revision = '6c2b133ef122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'FrameLabelTypes', ['labeltype'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
