"""framelabel : labeldate -> labeldatetime

Revision ID: 989ff97a6e7b
Revises: ea06a66ca0d4
Create Date: 2025-07-16 10:26:39.043085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '989ff97a6e7b'
down_revision = 'ea06a66ca0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labeldatetime', sa.DateTime(), nullable=True))
        batch_op.drop_column('labeldate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labeldate', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('labeldatetime')

    # ### end Alembic commands ###
