"""unique videoname in folder

Revision ID: a3d467166275
Revises: 1d28dd804e69
Create Date: 2024-12-30 14:40:11.766038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d467166275'
down_revision = '1d28dd804e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_folder_unique_constraint', ['name', 'folderId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_constraint('_name_folder_unique_constraint', type_='unique')

    # ### end Alembic commands ###
