"""rename user to account

Revision ID: a84c473b4a00
Revises: 5c977a30fd2e
Create Date: 2026-02-17 17:30:24.326433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a84c473b4a00'
down_revision = '5c977a30fd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=127), nullable=False),
    sa.Column('lastName', sa.String(length=127), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('mfaEnabled', sa.Boolean(), nullable=False),
    sa.Column('mfaCode', sa.String(length=6), nullable=True),
    sa.Column('mfaCodeExpires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=127), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=127), nullable=False),
    sa.Column('passwordHash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('lastLogin', mysql.DATETIME(), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.Column('mfaEnabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('mfaCode', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('mfaCodeExpires', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.drop_table('Accounts')
    # ### end Alembic commands ###
