"""longer framelength (so livestreams can be added)

Revision ID: aee0050a5cc6
Revises: 553f875bdce7
Create Date: 2025-01-16 15:17:24.591590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aee0050a5cc6'
down_revision = '553f875bdce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.alter_column('frameLength',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('Videos_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.create_foreign_key('Videos_ibfk_2', 'Sources', ['source'], ['id'])
        batch_op.alter_column('frameLength',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(unsigned=True),
               existing_nullable=False)

    # ### end Alembic commands ###
