"""adding default levels dd & cw

Revision ID: b9bdf7a05a5a
Revises: 50c9a0006f0b
Create Date: 2025-02-11 15:32:09.514763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9bdf7a05a5a'
down_revision = '50c9a0006f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_dd', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('level_cw', sa.String(length=7), nullable=False))
        batch_op.drop_column('level')

    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_dd', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('level_cw', sa.String(length=7), nullable=False))
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=7), nullable=False))
        batch_op.drop_column('level_cw')
        batch_op.drop_column('level_dd')

    with op.batch_alter_table('Skillinfo_DoubleDutch_Skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=7), nullable=False))
        batch_op.drop_column('level_cw')
        batch_op.drop_column('level_dd')

    # ### end Alembic commands ###
