"""Add composite unique constraint on name and parentId

Revision ID: ba5722aa4659
Revises: e84bc548939d
Create Date: 2024-12-24 13:27:51.127345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5722aa4659'
down_revision = 'e84bc548939d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_parent_unique_constraint', ['name', 'parentId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.drop_constraint('_name_parent_unique_constraint', type_='unique')

    # ### end Alembic commands ###
