"""LayerComposition add default value & focus mode

Revision ID: bc617d419a00
Revises: 537b5dd08060
Create Date: 2025-08-17 09:33:47.608792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc617d419a00'
down_revision = '537b5dd08060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LayerComposition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defaultValue', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('focussed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LayerComposition', schema=None) as batch_op:
        batch_op.drop_column('focussed')
        batch_op.drop_column('defaultValue')

    # ### end Alembic commands ###
