"""Update video privatable

Revision ID: c4d77e9f4be6
Revises: f13c9ea37582
Create Date: 2024-12-07 01:09:40.184705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d77e9f4be6'
down_revision = 'f13c9ea37582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
