"""framelabel : date, time & datetime

Revision ID: d35454169b5f
Revises: 989ff97a6e7b
Create Date: 2025-07-16 10:29:29.256751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35454169b5f'
down_revision = '989ff97a6e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labeldate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('labeltime', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FrameLabels', schema=None) as batch_op:
        batch_op.drop_column('labeltime')
        batch_op.drop_column('labeldate')

    # ### end Alembic commands ###
