"""Add skills

Revision ID: d6c43649b574
Revises: 80e434a0dfc0
Create Date: 2025-02-07 17:33:27.412699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6c43649b574'
down_revision = '80e434a0dfc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Skillinfo_DoubleDutch_Skill',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skillinfo_DoubleDutch_Turner',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skillinfo_DoubleDutch_Type',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skillinfo_DoubleDutch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('frameStart', sa.Integer(), nullable=False),
    sa.Column('frameEnd', sa.Integer(), nullable=False),
    sa.Column('type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('rotations', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('turner1', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('turner2', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('skill', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('hands', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('feet', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('turntable', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('bodyRotations', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('backwards', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('sloppy', mysql.TINYINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['skill'], ['Skillinfo_DoubleDutch_Skill.id'], ),
    sa.ForeignKeyConstraint(['turner1'], ['Skillinfo_DoubleDutch_Turner.id'], ),
    sa.ForeignKeyConstraint(['turner2'], ['Skillinfo_DoubleDutch_Turner.id'], ),
    sa.ForeignKeyConstraint(['type'], ['Skillinfo_DoubleDutch_Type.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Skillinfo_DoubleDutch')
    op.drop_table('Skillinfo_DoubleDutch_Type')
    op.drop_table('Skillinfo_DoubleDutch_Turner')
    op.drop_table('Skillinfo_DoubleDutch_Skill')
    # ### end Alembic commands ###
