"""add video.completed_skill_labels

Revision ID: e1d382ba58b9
Revises: 4d369a28c2d0
Create Date: 2025-02-14 18:28:04.624031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d382ba58b9'
down_revision = '4d369a28c2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_skill_labels', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_column('completed_skill_labels')

    # ### end Alembic commands ###
