"""Add framelabels

Revision ID: e2be7c916a96
Revises: 94224f7149ae
Create Date: 2024-12-28 00:30:08.529256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2be7c916a96'
down_revision = '94224f7149ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FrameLabels',
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('frameNr', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('jumperVisible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('videoId', 'frameNr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FrameLabels')
    # ### end Alembic commands ###
