"""Update folder parent

Revision ID: e84bc548939d
Revises: bdb4b32df0c1
Create Date: 2024-12-07 10:16:41.588668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e84bc548939d'
down_revision = 'bdb4b32df0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('Folders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Folders', ['parentId'], ['id'])
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Folders_ibfk_1', 'Folders', ['parent_id'], ['id'])
        batch_op.drop_column('parentId')

    # ### end Alembic commands ###
