"""adding default levels dd & cw

Revision ID: e9247e7070ae
Revises: 4ef14bf3ac25
Create Date: 2025-02-11 15:52:29.509042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9247e7070ae'
down_revision = '4ef14bf3ac25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Skill', schema=None) as batch_op:
        batch_op.alter_column('level_dd',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=127),
               existing_nullable=False)
        batch_op.alter_column('level_cw',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=127),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Skill', schema=None) as batch_op:
        batch_op.alter_column('level_cw',
               existing_type=sa.String(length=127),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.alter_column('level_dd',
               existing_type=sa.String(length=127),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
