"""init restart, after lagging composite PK framelabels

Revision ID: ea06a66ca0d4
Revises: 
Create Date: 2025-07-14 12:02:37.918448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea06a66ca0d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CompetitionInfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['Folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parentId', name='_name_parent_unique_constraint')
    )
    op.create_table('FrameLabelTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('step', sa.String(length=127), nullable=False),
    sa.Column('job_arguments', mysql.JSON(), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_details', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ML_Models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skillinfo_DoubleDutch_Skill',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('level_dd', sa.String(length=8), nullable=False),
    sa.Column('level_cw', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skillinfo_DoubleDutch_Turner',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('level_dd', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('level_cw', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('cw_requires_both', sa.Boolean(), nullable=False),
    sa.Column('dd_requires_both', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skillinfo_DoubleDutch_Type',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TagGroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('TrainResults',
    sa.Column('modelname', sa.String(length=127), nullable=False),
    sa.Column('train_date', sa.Integer(), nullable=False),
    sa.Column('epoch', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('iou', sa.Float(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('val_iou', sa.Float(), nullable=False),
    sa.Column('val_loss', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('modelname', 'epoch', name='_modelname_epoch_pk_constraint')
    )
    op.create_table('TrainResultsSkills',
    sa.Column('modelname', sa.String(length=127), nullable=False),
    sa.Column('train_date', sa.Integer(), nullable=False),
    sa.Column('epoch', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('val_loss', sa.Float(), nullable=False),
    sa.Column('val_accuracy', sa.Float(), nullable=False),
    sa.Column('losses_and_metrics', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('modelname', 'epoch', name='_modelname_epoch_pk_constraint')
    )
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('tagGroupId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tagGroupId'], ['TagGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folderId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frameLength', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('training', sa.Boolean(), nullable=False),
    sa.Column('qualitative', sa.Boolean(), nullable=False),
    sa.Column('obstruction', sa.Boolean(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('sourceInfo', sa.String(length=255), nullable=True),
    sa.Column('completed_skill_labels', sa.Boolean(), nullable=False),
    sa.Column('competition', sa.Integer(), nullable=True),
    sa.Column('judgeDiffScore', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['competition'], ['CompetitionInfo.id'], ),
    sa.ForeignKeyConstraint(['folderId'], ['Folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'folderId', name='_name_folder_unique_constraint')
    )
    op.create_table('FrameLabels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('frameNr', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('jumperVisible', sa.Boolean(), nullable=False),
    sa.Column('labeltype', sa.Integer(), nullable=False),
    sa.Column('labeldate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['labeltype'], ['FrameLabelTypes.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Predictions_Localization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('frameNr', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('x2', sa.Integer(), nullable=False),
    sa.Column('y2', sa.Integer(), nullable=False),
    sa.Column('locationChecked', sa.Boolean(), nullable=False),
    sa.Column('segmentSplitValue', sa.Float(), nullable=True),
    sa.Column('segmentsChecked', sa.Boolean(), nullable=False),
    sa.Column('predictionDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skillinfo_DoubleDutch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('frameStart', sa.Integer(), nullable=False),
    sa.Column('frameEnd', sa.Integer(), nullable=False),
    sa.Column('type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('rotations', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('turner1', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('turner2', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('skill', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('hands', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('feet', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('turntable', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('bodyRotations', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('backwards', sa.Boolean(), nullable=False),
    sa.Column('sloppy', sa.Boolean(), nullable=False),
    sa.Column('hard2see', sa.Boolean(), nullable=False),
    sa.Column('fault', sa.Boolean(), nullable=False),
    sa.Column('labeldate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill'], ['Skillinfo_DoubleDutch_Skill.id'], ),
    sa.ForeignKeyConstraint(['turner1'], ['Skillinfo_DoubleDutch_Turner.id'], ),
    sa.ForeignKeyConstraint(['turner2'], ['Skillinfo_DoubleDutch_Turner.id'], ),
    sa.ForeignKeyConstraint(['type'], ['Skillinfo_DoubleDutch_Type.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_tag',
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('tagId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tagId'], ['Tags.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('videoId', 'tagId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_tag')
    op.drop_table('Skillinfo_DoubleDutch')
    op.drop_table('Predictions_Localization')
    op.drop_table('FrameLabels')
    op.drop_table('Videos')
    op.drop_table('Tags')
    op.drop_table('TrainResultsSkills')
    op.drop_table('TrainResults')
    op.drop_table('TagGroups')
    op.drop_table('Sources')
    op.drop_table('Skillinfo_DoubleDutch_Type')
    op.drop_table('Skillinfo_DoubleDutch_Turner')
    op.drop_table('Skillinfo_DoubleDutch_Skill')
    op.drop_table('ML_Models')
    op.drop_table('Jobs')
    op.drop_table('FrameLabelTypes')
    op.drop_table('Folders')
    op.drop_table('CompetitionInfo')
    # ### end Alembic commands ###
