"""add l last Updated to ler properties, layer property value

Revision ID: eff7ee2a451a
Revises: 65c4ed988090
Create Date: 2025-07-25 12:41:41.416684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff7ee2a451a'
down_revision = '65c4ed988090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LayerProperties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastUpdated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('LayerPropertyValues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastUpdated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LayerPropertyValues', schema=None) as batch_op:
        batch_op.drop_column('lastUpdated')

    with op.batch_alter_table('LayerProperties', schema=None) as batch_op:
        batch_op.drop_column('lastUpdated')

    # ### end Alembic commands ###
