"""empty message

Revision ID: f13c9ea37582
Revises: 
Create Date: 2024-12-07 01:06:23.337618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13c9ea37582'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('Videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folderId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('training', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('obstruction', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['folderId'], ['Folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Videos')
    op.drop_table('Folders')
    # ### end Alembic commands ###
