"""competitioninfo year

Revision ID: f1b872d0d749
Revises: 049dd53c8894
Create Date: 2025-05-13 20:50:31.259644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b872d0d749'
down_revision = '049dd53c8894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CompetitionInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CompetitionInfo', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
