"""adding default levels dd & cw

Revision ID: fbded2d8de76
Revises: 075ec79e0e90
Create Date: 2025-02-11 15:37:37.479396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbded2d8de76'
down_revision = '075ec79e0e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.drop_column('level_cw')
        batch_op.drop_column('level_dd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skillinfo_DoubleDutch_Turner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_dd', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('level_cw', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
