# syntax=docker/dockerfile:1
# Stage 1: Build the Vue app
FROM node:20-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm install

# Expose port for dev server
EXPOSE ${WEB_LOCAL_PORT:-5173}

# Start Vue dev server
CMD sh -c "npm run dev"

